add_cus_dep('glo', 'gls', 0, 'run_makeglossaries');
add_cus_dep('acn', 'acr', 0, 'run_makeglossaries');

sub run_makeglossaries {
  ($b,$c) = $_[0] =~ m|^(.*[/\\])([^/\\]+?)$|;

  if ( $silent ) {
    system "makeglossaries -d build -q '$c'";
  }
  else {
    system "makeglossaries -d build '$c'";
  };
}

$pdf_mode = 1;
$pdflatex = 'lualatex -interaction=nonstopmode -halt-on-error %O %S';
$out_dir = 'build';

